import java.util.*;
import java.io.*;

public class GenerateReports {

    /** number of text files to be read, generated by CompileAndExecuteScript.sh */
    public static final int READ_TEXT_FILES = 6;

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Usage: java GenerateReports directory_name");
            System.exit(1);
        }
        
        File folder = new File(args[0]);
        if ( !folder.isDirectory() ) {
            System.out.println("Error: supplied directory not a directory.");
            System.exit(1);
        }
        
        //Folders inside the directory
        File[] folders = folder.listFiles();
        
        System.out.println(folders.length);
        
        //Files in each directory
        //[Number of folders][Number of text files to be read.]
        File[][] files = new File[folders.length][READ_TEXT_FILES];
        
        System.out.println(files.length);
        System.out.println(files[0].length);
        
        //Get files from each directory - the output.*.txt files specifically
        for (int i = 0; i < folders.length; i++ ) {
            files[i] = folders[i].listFiles(new FilenameFilter(){
                @Override
	            public boolean accept(File directory, String fileName) {
	                if (fileName.endsWith(".txt")) {
	                    return true;
	                }
	                return false;
	            }
	        } );
        }
        
        for ( int i = 0; i < folders.length; i++ ) {
        
            File report = new File("Report.txt");
        
        }
    
    }
    
    public static 

}
